name = "SphericalSpatialTrees"
uuid = "86b7679e-e8c0-4ea9-ad3d-baef5c69eb57"
authors = ["Fabian Gans <fgans@bgc-jena.mpg.de> and contributors"]
version = "0.1.0-DEV"

[deps]
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
DiskArrays = "3c3547ce-8d99-4f5e-a174-61eb10b00ae3"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
GeoFormatTypes = "68eda718-8dee-11e9-39e7-89f7f65f511f"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeometryOps = "3251bfac-6a57-4b6d-aa61-ac1fef2975ab"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Proj = "c94c279d-25a6-4763-9509-64d165bea63e"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
YAXArrays = "c21b50f5-aa40-41ea-b809-c0f5e47bfa5c"

[compat]
CoordinateTransformations = "0.6"
DimensionalData = "0.29"
DiskArrays = "0.4.16"
Distributed = "1"
GeoFormatTypes = "0.4"
GeoInterface = "1.5"
GeometryOps = "0.1.28"
LinearAlgebra = "1"
Proj = "1.9.0"
Rotations = "1.7"
StaticArrays = "1.9"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
